name: Development CD

on:
  repository_dispatch:
    types: [dev-ais-app-repository-dispatch]

jobs:
  build:
    runs-on: self-hosted:dev

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: This machine is sleepy
        run: |
          sleep 60