name: Development CD

on:
  repository_dispatch:
    types: [dev-ais-app-repository-dispatch]

jobs:
  build:
    runs-on: self-hosted:dev

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ais-dev-web-app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_385AC45CE73241FD98FF2CE20BC37F30 }}
          package: .
